import { createFileRoute, Link } from '@tanstack/react-router'
import type { ReactNode } from 'react'

import { LongformDoc, LONGFORM_SCROLL_MT, type DocSection } from '~/components/longform/LongformDoc'
import { seo } from '~/lib/seo'
import { PERSON_NAME } from '~/lib/site'
import { cn } from '~/lib/utils'

// Terms of service (§24.148). Google's OAuth consent screen has an optional ToS
// field; this satisfies it and governs use of the public showcase (the simulator +
// contact form). On the shared long-form scaffold, sibling to /privacy. Footer is
// left untouched (a footer link would force a fullPage @visual re-bless on every
// page) — it's reached from /privacy + used directly as the consent-screen ToS URL.
// Identity-safe: operator = build-time `PERSON_NAME`, contact via /contact.
export const Route = createFileRoute('/(marketing)/terms')({
  component: TermsPage,
  head: () =>
    seo({
      title: `Terms of Service — ${PERSON_NAME}`,
      description: 'The terms that govern use of this site and its live simulator.',
      path: '/terms',
    }),
})

const LAST_UPDATED = 'June 21, 2026'

const SECTIONS: DocSection[] = [
  { id: 'overview', title: 'These terms' },
  { id: 'use', title: 'Using this site' },
  { id: 'simulator', title: 'The live simulator' },
  { id: 'as-is', title: 'No warranty' },
  { id: 'contact', title: 'Changes & contact' },
]
const M = Object.fromEntries(SECTIONS.map((s) => [s.id, s])) as Record<string, DocSection>

function Sec({ section, children }: { section: DocSection; children: ReactNode }) {
  return (
    <section
      id={section.id}
      data-longform-section={section.id}
      aria-labelledby={`h-${section.id}`}
      className={cn('flex flex-col gap-3', LONGFORM_SCROLL_MT)}
    >
      <h2 id={`h-${section.id}`} className="text-lg font-semibold tracking-tight text-foreground">
        {section.title}
      </h2>
      {children}
    </section>
  )
}

function TermsPage() {
  return (
    <main data-testid="terms" className="mx-auto w-full max-w-4xl px-6 py-12">
      <header className="border-b border-border pb-6">
        <div className="flex items-baseline justify-between gap-4">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Terms of Service</h1>
          <span className="shrink-0 font-mono text-[11px] uppercase tracking-widest text-muted-foreground">
            The fine print
          </span>
        </div>
        <p className="mt-3 text-balance text-base leading-relaxed text-muted-foreground">
          The terms that govern use of this site — the personal hiring portal operated by {PERSON_NAME} — and its public
          features, the “watch it work” simulator and the contact form.
        </p>
        <p className="mt-3 font-mono text-[11px] text-muted-foreground/80">Last updated: {LAST_UPDATED}</p>
      </header>

      <div className="mt-8">
        <LongformDoc
          sections={SECTIONS}
          idPrefix="terms"
          navLabel="On this page"
          stepper
          contentClassName="flex flex-col gap-10"
        >
          <Sec section={M.overview}>
            <p className="leading-relaxed text-foreground/90">
              By using this site — browsing it, running the simulator, or sending a message through the contact form —
              you agree to these terms. If you don’t agree with them, please don’t use the site.
            </p>
          </Sec>

          <Sec section={M.use}>
            <p className="leading-relaxed text-foreground/90">
              You’re welcome to use the public features for their intended purpose: evaluating my work as a candidate.
              Please don’t attempt to disrupt, overload, attack, or gain unauthorized access to the service, don’t
              scrape it at scale, and don’t submit content that is unlawful or abusive. The simulator and the contact
              form are rate-limited and protected against abuse.
            </p>
          </Sec>

          <Sec section={M.simulator}>
            <p className="leading-relaxed text-foreground/90">
              The “watch it work” run generates a sample, AI-tailored résumé and outreach email for the role you enter.
              It’s an illustration of how my agent works — not a job application, a binding offer, or professional
              advice. Its output is generated by an AI model and may contain mistakes; treat it as a demonstration. The
              company, role, and job description you enter are processed by an AI provider and stored privately for a
              short window — see the{' '}
              <Link to="/privacy" className="text-accent-cool hover:underline">
                privacy policy
              </Link>
              .
            </p>
          </Sec>

          <Sec section={M['as-is']}>
            <p className="leading-relaxed text-foreground/90">
              This site is provided “as is,” without warranties of any kind. I work to keep it accurate and available,
              but I don’t guarantee it will be error-free or uninterrupted, and to the extent the law allows I’m not
              liable for any loss arising from its use.
            </p>
          </Sec>

          <Sec section={M.contact}>
            <p className="leading-relaxed text-foreground/90">
              I may update these terms; the date above reflects the latest version. See also the{' '}
              <Link to="/privacy" className="text-accent-cool hover:underline">
                Privacy policy
              </Link>
              . Questions can go through{' '}
              <Link to="/contact" search={{ from: 'terms' }} className="text-accent-cool hover:underline">
                the contact form
              </Link>
              .
            </p>
          </Sec>
        </LongformDoc>
      </div>
    </main>
  )
}
