/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as opsLiveRouteImport } from './routes/(ops)/live'
import { Route as opsFunnelRouteImport } from './routes/(ops)/funnel'
import { Route as opsArchitectureRouteImport } from './routes/(ops)/architecture'
import { Route as marketingWorkRouteImport } from './routes/(marketing)/work'

const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const opsLiveRoute = opsLiveRouteImport.update({
  id: '/(ops)/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const opsFunnelRoute = opsFunnelRouteImport.update({
  id: '/(ops)/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const opsArchitectureRoute = opsArchitectureRouteImport.update({
  id: '/(ops)/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingWorkRoute = marketingWorkRouteImport.update({
  id: '/(marketing)/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/work': typeof marketingWorkRoute
  '/architecture': typeof opsArchitectureRoute
  '/funnel': typeof opsFunnelRoute
  '/live': typeof opsLiveRoute
  '/': typeof marketingIndexRoute
}
export interface FileRoutesByTo {
  '/work': typeof marketingWorkRoute
  '/architecture': typeof opsArchitectureRoute
  '/funnel': typeof opsFunnelRoute
  '/live': typeof opsLiveRoute
  '/': typeof marketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)/work': typeof marketingWorkRoute
  '/(ops)/architecture': typeof opsArchitectureRoute
  '/(ops)/funnel': typeof opsFunnelRoute
  '/(ops)/live': typeof opsLiveRoute
  '/(marketing)/': typeof marketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/work' | '/architecture' | '/funnel' | '/live' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/work' | '/architecture' | '/funnel' | '/live' | '/'
  id:
    | '__root__'
    | '/(marketing)/work'
    | '/(ops)/architecture'
    | '/(ops)/funnel'
    | '/(ops)/live'
    | '/(marketing)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingWorkRoute: typeof marketingWorkRoute
  opsArchitectureRoute: typeof opsArchitectureRoute
  opsFunnelRoute: typeof opsFunnelRoute
  opsLiveRoute: typeof opsLiveRoute
  marketingIndexRoute: typeof marketingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ops)/live': {
      id: '/(ops)/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof opsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ops)/funnel': {
      id: '/(ops)/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof opsFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ops)/architecture': {
      id: '/(ops)/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof opsArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/work': {
      id: '/(marketing)/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof marketingWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  marketingWorkRoute: marketingWorkRoute,
  opsArchitectureRoute: opsArchitectureRoute,
  opsFunnelRoute: opsFunnelRoute,
  opsLiveRoute: opsLiveRoute,
  marketingIndexRoute: marketingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
