/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as opsRouteRouteImport } from './routes/(ops)/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as opsMomentumRouteImport } from './routes/(ops)/momentum'
import { Route as opsLiveRouteImport } from './routes/(ops)/live'
import { Route as opsDevRouteImport } from './routes/(ops)/dev'
import { Route as opsCrashRouteImport } from './routes/(ops)/crash'
import { Route as opsArchitectureRouteImport } from './routes/(ops)/architecture'
import { Route as marketingWorkRouteImport } from './routes/(marketing)/work'
import { Route as marketingContactRouteImport } from './routes/(marketing)/contact'
import { Route as marketingSimulatorIndexRouteImport } from './routes/(marketing)/simulator.index'
import { Route as marketingSimulatorResultsIdRouteImport } from './routes/(marketing)/simulator.results.$id'

const opsRouteRoute = opsRouteRouteImport.update({
  id: '/(ops)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const opsMomentumRoute = opsMomentumRouteImport.update({
  id: '/momentum',
  path: '/momentum',
  getParentRoute: () => opsRouteRoute,
} as any)
const opsLiveRoute = opsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => opsRouteRoute,
} as any)
const opsDevRoute = opsDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => opsRouteRoute,
} as any)
const opsCrashRoute = opsCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => opsRouteRoute,
} as any)
const opsArchitectureRoute = opsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => opsRouteRoute,
} as any)
const marketingWorkRoute = marketingWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingContactRoute = marketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingSimulatorIndexRoute = marketingSimulatorIndexRouteImport.update({
  id: '/simulator/',
  path: '/simulator/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingSimulatorResultsIdRoute =
  marketingSimulatorResultsIdRouteImport.update({
    id: '/simulator/results/$id',
    path: '/simulator/results/$id',
    getParentRoute: () => marketingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/contact': typeof marketingContactRoute
  '/work': typeof marketingWorkRoute
  '/architecture': typeof opsArchitectureRoute
  '/crash': typeof opsCrashRoute
  '/dev': typeof opsDevRoute
  '/live': typeof opsLiveRoute
  '/momentum': typeof opsMomentumRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof marketingIndexRoute
  '/simulator/': typeof marketingSimulatorIndexRoute
  '/simulator/results/$id': typeof marketingSimulatorResultsIdRoute
}
export interface FileRoutesByTo {
  '/contact': typeof marketingContactRoute
  '/work': typeof marketingWorkRoute
  '/architecture': typeof opsArchitectureRoute
  '/crash': typeof opsCrashRoute
  '/dev': typeof opsDevRoute
  '/live': typeof opsLiveRoute
  '/momentum': typeof opsMomentumRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof marketingIndexRoute
  '/simulator': typeof marketingSimulatorIndexRoute
  '/simulator/results/$id': typeof marketingSimulatorResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/(ops)': typeof opsRouteRouteWithChildren
  '/(marketing)/contact': typeof marketingContactRoute
  '/(marketing)/work': typeof marketingWorkRoute
  '/(ops)/architecture': typeof opsArchitectureRoute
  '/(ops)/crash': typeof opsCrashRoute
  '/(ops)/dev': typeof opsDevRoute
  '/(ops)/live': typeof opsLiveRoute
  '/(ops)/momentum': typeof opsMomentumRoute
  '/api/$': typeof ApiSplatRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/(marketing)/simulator/': typeof marketingSimulatorIndexRoute
  '/(marketing)/simulator/results/$id': typeof marketingSimulatorResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/contact'
    | '/work'
    | '/architecture'
    | '/crash'
    | '/dev'
    | '/live'
    | '/momentum'
    | '/api/$'
    | '/'
    | '/simulator/'
    | '/simulator/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/work'
    | '/architecture'
    | '/crash'
    | '/dev'
    | '/live'
    | '/momentum'
    | '/api/$'
    | '/'
    | '/simulator'
    | '/simulator/results/$id'
  id:
    | '__root__'
    | '/(marketing)'
    | '/(ops)'
    | '/(marketing)/contact'
    | '/(marketing)/work'
    | '/(ops)/architecture'
    | '/(ops)/crash'
    | '/(ops)/dev'
    | '/(ops)/live'
    | '/(ops)/momentum'
    | '/api/$'
    | '/(marketing)/'
    | '/(marketing)/simulator/'
    | '/(marketing)/simulator/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  opsRouteRoute: typeof opsRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(ops)': {
      id: '/(ops)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof opsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ops)/momentum': {
      id: '/(ops)/momentum'
      path: '/momentum'
      fullPath: '/momentum'
      preLoaderRoute: typeof opsMomentumRouteImport
      parentRoute: typeof opsRouteRoute
    }
    '/(ops)/live': {
      id: '/(ops)/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof opsLiveRouteImport
      parentRoute: typeof opsRouteRoute
    }
    '/(ops)/dev': {
      id: '/(ops)/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof opsDevRouteImport
      parentRoute: typeof opsRouteRoute
    }
    '/(ops)/crash': {
      id: '/(ops)/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof opsCrashRouteImport
      parentRoute: typeof opsRouteRoute
    }
    '/(ops)/architecture': {
      id: '/(ops)/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof opsArchitectureRouteImport
      parentRoute: typeof opsRouteRoute
    }
    '/(marketing)/work': {
      id: '/(marketing)/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof marketingWorkRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/contact': {
      id: '/(marketing)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof marketingContactRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/simulator/': {
      id: '/(marketing)/simulator/'
      path: '/simulator'
      fullPath: '/simulator/'
      preLoaderRoute: typeof marketingSimulatorIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/simulator/results/$id': {
      id: '/(marketing)/simulator/results/$id'
      path: '/simulator/results/$id'
      fullPath: '/simulator/results/$id'
      preLoaderRoute: typeof marketingSimulatorResultsIdRouteImport
      parentRoute: typeof marketingRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingContactRoute: typeof marketingContactRoute
  marketingWorkRoute: typeof marketingWorkRoute
  marketingIndexRoute: typeof marketingIndexRoute
  marketingSimulatorIndexRoute: typeof marketingSimulatorIndexRoute
  marketingSimulatorResultsIdRoute: typeof marketingSimulatorResultsIdRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingContactRoute: marketingContactRoute,
  marketingWorkRoute: marketingWorkRoute,
  marketingIndexRoute: marketingIndexRoute,
  marketingSimulatorIndexRoute: marketingSimulatorIndexRoute,
  marketingSimulatorResultsIdRoute: marketingSimulatorResultsIdRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface opsRouteRouteChildren {
  opsArchitectureRoute: typeof opsArchitectureRoute
  opsCrashRoute: typeof opsCrashRoute
  opsDevRoute: typeof opsDevRoute
  opsLiveRoute: typeof opsLiveRoute
  opsMomentumRoute: typeof opsMomentumRoute
}

const opsRouteRouteChildren: opsRouteRouteChildren = {
  opsArchitectureRoute: opsArchitectureRoute,
  opsCrashRoute: opsCrashRoute,
  opsDevRoute: opsDevRoute,
  opsLiveRoute: opsLiveRoute,
  opsMomentumRoute: opsMomentumRoute,
}

const opsRouteRouteWithChildren = opsRouteRoute._addFileChildren(
  opsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  opsRouteRoute: opsRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
