import { SITE_URL } from '~/lib/site'

// The shared social-meta layer (PORTAL §12, STRATEGY §24.36 36.5). One source of
// truth so every route's `head()` emits a complete + consistent set instead of
// hand-rolling tags that drift. Generic persona only — never real identifiers
// ([[project_generic_persona]]); the real name/domain/headshot arrive at deploy.

const SITE_NAME = 'Career Pilot'
const DEFAULT_DESCRIPTION =
  'An AI agent runs my job search — live. Watch it research companies, tailor a resume, and draft outreach, then run it on your own role.'
/** The branded static card (1200×630), generated by scripts/generate-og.mjs. */
const DEFAULT_IMAGE = '/og.png'

interface SeoInput {
  /** The full document title (each route owns its phrasing, e.g. "Dashboard — Jane Doe"). */
  title: string
  description?: string
  /** Absolute URL or a site-root path (turned absolute against SITE_URL). */
  image?: string
  /** The route's path (e.g. "/live") → absolute og:url. Omit for the home origin. */
  path?: string
}

type MetaTag = { title: string } | { name: string; content: string } | { property: string; content: string }

function absolute(urlOrPath: string): string {
  return urlOrPath.startsWith('http') ? urlOrPath : `${SITE_URL}${urlOrPath}`
}

/**
 * Build a route `head()` payload: `<title>` + description + the Open Graph set
 * (`og:title`/`description`/`type`/`site_name`/`image`/`url`) + the Twitter-card
 * set (`summary_large_image` + title/description/image). og:image / og:url are
 * absolute (social scrapers reject relative URLs).
 */
export function seo({ title, description = DEFAULT_DESCRIPTION, image = DEFAULT_IMAGE, path }: SeoInput): {
  meta: MetaTag[]
} {
  const img = absolute(image)
  const url = absolute(path ?? '/')
  return {
    meta: [
      { title },
      { name: 'description', content: description },
      { property: 'og:title', content: title },
      { property: 'og:description', content: description },
      { property: 'og:type', content: 'website' },
      { property: 'og:site_name', content: SITE_NAME },
      { property: 'og:image', content: img },
      { property: 'og:url', content: url },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: title },
      { name: 'twitter:description', content: description },
      { name: 'twitter:image', content: img },
    ],
  }
}
